spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:0000}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

  servlet:
    multipart:
      max-file-size: 5MB    # 파일 하나당 최대 크기
      max-request-size: 10MB # 요청 전체(Body) 최대 크기

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일

springdoc:
  swagger-ui:
    path: /docs

server:
  tomcat:
    max-swallow-size: 10MB # 톰캣단에서 제한

